server:
  port: 8081
spring:
  application:
    name: Foodie-Odyssey
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fo?useSSL=false&serverTimezone=UTC
    username: root
    password: jwj1554965857
  redis:
    host: 49.235.142.165
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: org.jwj.fo.entity # 别名扫描包
logging:
  level:
    org.jwj.fo: debug